//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZtxFrameWork.UI.Comm {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CommonResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommonResources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ZtxFrameWork.UI.Comm.CommonResources", typeof(CommonResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 确认要审核 {0}? 的本地化字符串。
        /// </summary>
        internal static string Confirmation_Audit {
            get {
                return ResourceManager.GetString("Confirmation_Audit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认 的本地化字符串。
        /// </summary>
        internal static string Confirmation_Caption {
            get {
                return ResourceManager.GetString("Confirmation_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认要生效 {0}? 的本地化字符串。
        /// </summary>
        internal static string Confirmation_Confirm {
            get {
                return ResourceManager.GetString("Confirmation_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认要删除 {0}? 的本地化字符串。
        /// </summary>
        internal static string Confirmation_Delete {
            get {
                return ResourceManager.GetString("Confirmation_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 点击确认放弃更改并重新加载数据。点击取消继续编辑数据。 的本地化字符串。
        /// </summary>
        internal static string Confirmation_Reset {
            get {
                return ResourceManager.GetString("Confirmation_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 需要保存更改吗? 的本地化字符串。
        /// </summary>
        internal static string Confirmation_Save {
            get {
                return ResourceManager.GetString("Confirmation_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认要取消审核 {0}? 的本地化字符串。
        /// </summary>
        internal static string Confirmation_UnAudit {
            get {
                return ResourceManager.GetString("Confirmation_UnAudit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认要失效 {0}? 的本地化字符串。
        /// </summary>
        internal static string Confirmation_UnConfirm {
            get {
                return ResourceManager.GetString("Confirmation_UnConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  * 的本地化字符串。
        /// </summary>
        internal static string Entity_Changed {
            get {
                return ResourceManager.GetString("Entity_Changed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  (新增) 的本地化字符串。
        /// </summary>
        internal static string Entity_New {
            get {
                return ResourceManager.GetString("Entity_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据层请求出错 的本地化字符串。
        /// </summary>
        internal static string Exception_DataServiceRequestErrorCaption {
            get {
                return ResourceManager.GetString("Exception_DataServiceRequestErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据保存出错 的本地化字符串。
        /// </summary>
        internal static string Exception_UpdateErrorCaption {
            get {
                return ResourceManager.GetString("Exception_UpdateErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据验证出错 的本地化字符串。
        /// </summary>
        internal static string Exception_ValidationErrorCaption {
            get {
                return ResourceManager.GetString("Exception_ValidationErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 等待 的本地化字符串。
        /// </summary>
        internal static string Warning_Caption {
            get {
                return ResourceManager.GetString("Warning_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 包含无效数据。单击确认放弃更改并关闭页面。按取消继续编辑数据。 的本地化字符串。
        /// </summary>
        internal static string Warning_SomeFieldsContainInvalidData {
            get {
                return ResourceManager.GetString("Warning_SomeFieldsContainInvalidData", resourceCulture);
            }
        }
    }
}
